version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '09:00'
      timezone: 'America/Sao_Paulo'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '09:00'
      timezone: 'America/Sao_Paulo'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '09:00'
      timezone: 'America/Sao_Paulo'
    commit-message:
      prefix: 'ci'
      include: 'scope'
