version: '3.9'

services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
    entrypoint: /code/scripts/entrypoints/local.sh
    ports:
      - '8080:8080'
    volumes:
      - ./:/code
