name: Pull Request

on:
  # Run when PRs are opened, synchronized or reopened
  pull_request:
    branches:
      - main
    # Changes done to these paths are ignored, no jobs are run
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - '.husky/**'
      - '.vscode/**'
      - 'docs/**'
      - 'internals/**'
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run eslint

      # - name: Stylelint
      #   run: npm run stylelint

      - name: Prettier
        run: npm run prettier

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:ci

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
